/* V15__par_verify_nullable.sql
   배포 환경에서 간단 검증용. 실패해도 애플리케이션엔 영향 없습니다.
*/
-- 컬럼 NULL 허용 상태 확인
SELECT COLUMN_NAME, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'professor_assignment_request'
  AND COLUMN_NAME = 'project_id';

-- FK 목록 확인
SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'professor_assignment_request'
  AND REFERENCED_TABLE_NAME IS NOT NULL;
