name: backend-ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  push:
    branches: [ main, moinji_premerge ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build backend
        run: ./mvnw -B -ntp -DskipTests package